# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set([('profile', 'on')]),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set([('profile', 'on')]),
        ),
    ]
