# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0002_auto_20180104_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentMessages', to='socialMedia.Profile')),
                ('toProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedMessages', to='socialMedia.Profile')),
            ],
        ),
    ]
