# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0003_auto_20180114_0207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='fromProfile',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='toProfile',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='toProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receivedMessages', to='socialMedia.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
