# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0005_auto_20180105_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile',
            new_name='owner',
        ),
    ]
