# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0006_profile_profilepicturesmall'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePictureNormal',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePictureThumb',
            field=models.ImageField(blank=True, editable=False, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
