# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import socialMedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0007_auto_20180114_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=socialMedia.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePictureNormal',
            field=models.ImageField(blank=True, editable=False, upload_to=socialMedia.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePictureSmall',
            field=models.ImageField(blank=True, editable=False, upload_to=socialMedia.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePictureThumb',
            field=models.ImageField(blank=True, editable=False, upload_to=socialMedia.models.user_directory_path),
        ),
    ]
