# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0008_auto_20180114_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
