# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0010_auto_20180115_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
